### ISSUE TITLE
Add `localStorage` to keep track of in-progress crafting sessions

### ISSUE THREAD

**Issue by jguluarte** [FFXIVCrafting/ffxivcrafting#268]
If a user has logged data on a crafting page for any number of classes, it would be nice to maintain the state of each item in localStorage.  This will allow the page to persist across browser sessions.

Specifically, this is to remember which items have been checked, which items are partially collected.

**Comment by Tickthokk** [comment]
This has been completed!  Huzzah :dancer: :dancer: :dancer:
