### ISSUE TITLE
Talan does not 'sell' items

### ISSUE THREAD

**Issue by uberfuzzy** [FFXIVCrafting/ffxivcrafting#290]
the mor dhona npc Talan is listed as "selling" stuffed artichoke and spinach quiche for coin. this is not true. he requires 5 silver sovereign for the former and 5 gigant clam for the latter.

**Comment by Tickthokk** [comment]
Got it, I'm now excluding Traders (non-gil vendors) from the Purchase list.  I'll make a separate ticket to include those types in, but for now they'll be excluded.

(update will go live in the next few days; closing ticket)
