### ISSUE TITLE
Leve page not loading

### ISSUE THREAD

**Issue by kizlan** [FFXIVCrafting/ffxivcrafting#293]
The leve quest list at http://www.craftingasaservice.com/levequests is loading a blank page for me. The issue is persisting over 3 browsers (Firefox, Chrome, and MS Edge) on two computers.

![untitled](https://cloud.githubusercontent.com/assets/16255284/11743906/1cb1e302-9fc0-11e5-894b-b16307cf524c.jpg)

**Comment by Tickthokk** [comment]
Thanks, I'm aware.  It's a tricky bug as it works locally but not on production.

Related reddit thread: https://www.reddit.com/r/ffxivcrafting/comments/3vlsos/levequests_page_is_completely_blank/

**Comment by Tickthokk** [comment]
Fixed!
