### ISSUE TITLE
MySQL server error

### ISSUE THREAD

**Issue by lurbyjo** [FFXIVCrafting/ffxivcrafting#300]
SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'd792e90bbc00dfae3676c321ee16240a4454aa4b.rackspaceclouddb.com' (111)

This is what I'm getting using any of the links on the site this evening (6/20/16 12:25 am MDT).

Thank you!

**Comment by Tickthokk** [comment]
Looks like it fixed itself.  Thanks for the ticket!

**Comment by lurbyjo** [comment]
It sure did! I was lost without it. <3

Thank you!

On Mon, Jun 20, 2016 at 4:21 AM, Nick Wright <notifications@github.com>
wrote:

> Looks like it fixed itself. Thanks for the ticket!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FFXIVCrafting/ffxivcrafting/issues/300#issuecomment-227104690>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AROCYW3Tuo7zNVtemD1Axd_-4COViCakks5qNmmogaJpZM4I5ZN1>
> .
>



-- 
... ... ... ... ...
"Go then, there are other worlds than these."  --Jake Chambers, The
Gunslinger
