### ISSUE TITLE
Wrong target for language links

### ISSUE THREAD

**Issue by Supamiu** [FFXIVCrafting/ffxivcrafting#309]
When you change language in the navbar (from english to french for instance) the link points to `fr.<current url>`.

If the current url is `www.craftingasaservice.com` the link redirects to `fr.www.craftingasaservice.com` which leads to a 404 error.

Steps to reproduce:

- Go to www.craftingasaservice.com
- Change language to French

**Comment by Ninjistix** [comment]
can also confirm all language changes take you to 
> fr.www.craftingasaservice.com
> de.www.craftingasaservice.com
> ja.www.craftingasaservice.com

seems the intended target should be 
> fr.craftingasaservice.com
> de.craftingasaservice.com
> ja.craftingasaservice.com

but all 3 of those links are still in English (although the page language said it was changed).

**Comment by Tickthokk** [comment]
Thanks for the reports!  I've got this fixed, but it might be a bit before it goes live.

**Comment by Ninjistix** [comment]
@Tickthokk did you see that, when changing the language on http://craftingasaservice.com/ it still stays English?

**Comment by Tickthokk** [comment]
The site content stays english, yes, but that's true for all the site text anyway.  There's no language stuff for that unfortunately.

The stuff that matters, item names, etc, are what changes.

**Comment by Ninjistix** [comment]
my bad I figured the general site text was translated also, I've never tired to switch languages before now
